### ISSUE TITLE
homogénéité des clés

### ISSUE THREAD

**Issue by edhil** [vengaar/dd3#6]
Pour la description des pouvoirs, la clé "desc" est affichée
Pour la description de l'équipement, la clé "desc" n'est pas affichée, ce qui pourrait etre interessant pour completer la liste des pouvoirs. 

Sinon pour les dons et l'équipement (et plus tard les sorts) il pourrait etre interessant d'ajouter la clé "book" permettant d'indiquer quel est le livre qui règle qui décrit la capacité en question, lorsque la description n'est pas en ligne.

**Comment by vengaar** [comment]
La description est maintenant affiché pour l'équipement

**Comment by vengaar** [comment]
Pour book pourquoi pas mais du il y aurait book + url c'est une redondant non ?
Pourquoi pas plutot remplacer les 2 champs par un seul, genre "reference" ou "ref" dans lequel ou pourait mettre sont une url soit tu text ?

**Comment by edhil** [comment]
Ok pour "reference" a la place de "url". Mais dans ce cas il serait bon qu'on puisse en mettre plusieurs, on sait jamais.

**Comment by vengaar** [comment]
Implémenté sous forme de liste avec du la clef "references" avec un "s"
Marche pour les pouvoirs et l’équipement.
Exemple sur Seleniel avec 2 pouvoirs de druide (Empathie sauvage et Instinct naturel) et le bâton de forêt profonde.
Si plusieurs lien http sont fourni, c'est le premier qui sert de lien sur le nom du pouvoir ou de l’équipement.

Sinon la 5ieme édition a une API pour tout récupérer... https://www.aidedd.org/dnd/om.php?vf=baton-des-forets
